name: Release
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: false
        default: "warning"

permissions: write-all

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.*
      - name: Install pnpm
        run: |
          curl -f https://get.pnpm.io/v6.14.js | node - add --global pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Pull from Notion
        env:
          DOCU_NOTION_INTEGRATION_TOKEN: ${{ secrets.DOCU_NOTION_INTEGRATION_TOKEN }}
          DOCU_NOTION_DOCS_ROOT_PAGE_EN: ${{ secrets.DOCU_NOTION_DOCS_ROOT_PAGE_EN }}
          DOCU_NOTION_BLOG_ROOT_PAGE_EN: ${{ secrets.DOCU_NOTION_BLOG_ROOT_PAGE_EN }}
          DOCU_NOTION_DOCS_ROOT_PAGE_HANT: ${{ secrets.DOCU_NOTION_DOCS_ROOT_PAGE_HANT }}
          DOCU_NOTION_BLOG_ROOT_PAGE_HANT: ${{ secrets.DOCU_NOTION_BLOG_ROOT_PAGE_HANT }}
          DOCU_NOTION_DOCS_ROOT_PAGE_KO: ${{ secrets.DOCU_NOTION_DOCS_ROOT_PAGE_KO }}
          DOCU_NOTION_BLOG_ROOT_PAGE_KO: ${{ secrets.DOCU_NOTION_BLOG_ROOT_PAGE_KO }}
        run: pnpm run pull
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply changes from docu-notion